app: myapp
env: local
namespace: default
chart:
  name: https://github.com/laszlocph/onechart.git?branch=master&path=/charts/onechart/
values:
  replicas: 3
  image:
    repository: ghcr.io/podtato-head/podtatoserver
    tag: "v0.1.1"
  gitRepository: laszlocph/gimletd-test-repo
  gitSha: "{{ .SHA }}"
