app: myapp
env: local
namespace: default
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.24.0
values:
  replicas: 3
  image:
    repository: ghcr.io/podtato-head/podtatoserver
    tag: "v0.1.1"
  gitRepository: laszlocph/gimletd-test-repo
  gitSha: "{{ .SHA }}"
