app: myapp
env: staging
namespace: gimlet-demo-staging
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.24.0
deploy:
  event: tag
  tag: v*
values:
  replicas: 1
  image:
    repository: myapp
    tag: "{{ .GITHUB_SHA }}"
  gitRepository: laszlocph/gimletd-test-repo
  gitSha: "{{ .GITHUB_SHA }}"
