app: myapp
env: staging
namespace: staging
chart:
    repository: https://chart.onechart.dev
    name: onechart
    version: 0.32.0
values:
    gitRepository: gimlet-io/test-app
    gitSha: '{{ .GITHUB_SHA }}'
    image:
        repository: ghcr.io/podtato-head/podtatoserver
        tag: v0.1.1
    replicas: 3
strategicMergePatches: ""
json6902Patches: []
manifests: ""
