app: test-app
env: staging
namespace: staging
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.36.0
values:
  containerPort: 9000
  gitRepository: gimlet-io/test-app
  gitSha: '{{ .GITHUB_SHA }}'
  image:
    repository: ghcr.io/gimlet-io/test-app
    tag: '{{ .GITHUB_SHA }}'
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx
    host: test-app.staging.turbopizza.net
    tlsEnabled: true
  replicas: 10
strategicMergePatches: ""
json6902Patches: []
manifests: ""
