app: myapp
env: staging
namespace: staging
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.32.0
values:
  replicas: 2
  image:
    repository: ghcr.io/podtato-head/podtatoserver
    tag: "v0.1.1"
  gitRepository: gimlet-io/test-app
  gitSha: "{{ .GITHUB_SHA }}"
