app: myapp
env: staging
namespace: gimlet-demo-staging
chart:
  name: git@github.com:laszlocph/onechart.git?branch=master&path=/charts/onechart/
deploy:
  event: tag
  tag: v*
values:
  replicas: 3
  image:
    repository: ghcr.io/podtato-head/podtatoserver
    tag: "v0.1.1"
  gitRepository: laszlocph/gimletd-test-repo
  gitSha: "{{ .GITHUB_SHA }}"
