app: test-app
env: staging
namespace: staging
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.36.0
values:
  containerPort: 9000
  gitRepository: gimlet-io/test-app
  gitSha: '{{ .GITHUB_SHA }}'
  image:
    repository: ghcr.io/podtato-head/podtatoserver
    tag: v0.1.1
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
    host: test-app.staging.gimlet.io
    tlsEnabled: true
  replicas: 2
strategicMergePatches: ""
json6902Patches: []
manifests: ""
