app: myapp
env: staging
namespace: gimlet-demo-staging
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.31.0
deploy:
  event: tag
  tag: v*
values:
  replicas: 2
  image:
    repository: ghcr.io/podtato-head/podtatoserver
    tag: "v0.1.1"
  gitRepository: laszlocph/gimletd-test-repo
  gitSha: "{{ .GITHUB_SHA }}"
  podAnnotations:
    testing: "{{ .url }}"
