name: Build
on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - '*'

  create:
    tags:
      - v*

jobs:
  build:
    name: Demo
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Demo
      id: demo
      uses: gimlet-io/gimlet-artifact-shipper-action@v0.3.13
      env:
        GIMLET_SERVER: ${{ secrets.GIMLET_SERVER }}
        GIMLET_TOKEN: ${{ secrets.GIMLET_TOKEN }}
    - name: Artifact ID
      run: echo "Artifact ID is ${{ steps.demo.outputs.artifact-id }}"
